/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrievs a ticket
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken"> (optional)</param>
        /// <param name="category"> (optional)</param>
        /// <param name="statuses"> (optional)</param>
        /// <param name="orderedColumn"> (optional)</param>
        /// <param name="orderedBy"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Ticket</returns>
        Ticket GetTicket (string ticketId, string authenticationToken = null, string category = null, string statuses = null, string orderedColumn = null, string orderedBy = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrievs a ticket
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken"> (optional)</param>
        /// <param name="category"> (optional)</param>
        /// <param name="statuses"> (optional)</param>
        /// <param name="orderedColumn"> (optional)</param>
        /// <param name="orderedBy"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>ApiResponse of Ticket</returns>
        ApiResponse<Ticket> GetTicketWithHttpInfo (string ticketId, string authenticationToken = null, string category = null, string statuses = null, string orderedColumn = null, string orderedBy = null, string clientId = null, string clientSecret = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="start">Start query value (optional)</param>
        /// <param name="length">Number of rows query (optional)</param>
        /// <param name="draw">Number of times table has been reloaded (optional)</param>
        /// <param name="q">Values provided in q are tokenized and search on columns: TICKET_ID,SUBJECT,REQUESTOR_UERNAME, REQUESTOR_EMAIL, TICKET_MESSAGES (optional)</param>
        /// <param name="sortBy">Column name to order table by (optional)</param>
        /// <param name="sortByOrder">Sort by ascending or descending (optional)</param>
        /// <param name="passedAccountId"> (optional)</param>
        /// <param name="passedUserId"> (optional)</param>
        /// <param name="viewId">View Id (optional)</param>
        /// <param name="clientId">API ID (optional)</param>
        /// <param name="clientSecret">API Secret (optional)</param>
        /// <returns>List&lt;Ticket&gt;</returns>
        List<Ticket> GetTickets (decimal? authenticationToken = null, int? start = null, int? length = null, int? draw = null, string q = null, string sortBy = null, string sortByOrder = null, string passedAccountId = null, string passedUserId = null, int? viewId = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="start">Start query value (optional)</param>
        /// <param name="length">Number of rows query (optional)</param>
        /// <param name="draw">Number of times table has been reloaded (optional)</param>
        /// <param name="q">Values provided in q are tokenized and search on columns: TICKET_ID,SUBJECT,REQUESTOR_UERNAME, REQUESTOR_EMAIL, TICKET_MESSAGES (optional)</param>
        /// <param name="sortBy">Column name to order table by (optional)</param>
        /// <param name="sortByOrder">Sort by ascending or descending (optional)</param>
        /// <param name="passedAccountId"> (optional)</param>
        /// <param name="passedUserId"> (optional)</param>
        /// <param name="viewId">View Id (optional)</param>
        /// <param name="clientId">API ID (optional)</param>
        /// <param name="clientSecret">API Secret (optional)</param>
        /// <returns>ApiResponse of List&lt;Ticket&gt;</returns>
        ApiResponse<List<Ticket>> GetTicketsWithHttpInfo (decimal? authenticationToken = null, int? start = null, int? length = null, int? draw = null, string q = null, string sortBy = null, string sortByOrder = null, string passedAccountId = null, string passedUserId = null, int? viewId = null, string clientId = null, string clientSecret = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Insert a messages
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken">User athentication (optional)</param>
        /// <param name="clientId">api client (optional)</param>
        /// <param name="clientSecret">api secret (optional)</param>
        /// <returns></returns>
        void PostMessages (Ticket body, string ticketId, string authenticationToken = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Insert a messages
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken">User athentication (optional)</param>
        /// <param name="clientId">api client (optional)</param>
        /// <param name="clientSecret">api secret (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PostMessagesWithHttpInfo (Ticket body, string ticketId, string authenticationToken = null, string clientId = null, string clientSecret = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Insert a tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Ticket</returns>
        Ticket PostTickets (List<TicketMessage> body, decimal? authenticationToken = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Insert a tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>ApiResponse of Ticket</returns>
        ApiResponse<Ticket> PostTicketsWithHttpInfo (List<TicketMessage> body, decimal? authenticationToken = null, string clientId = null, string clientSecret = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>List&lt;Ticket&gt;</returns>
        List<Ticket> PutTickets (List<Ticket> body, bool? authenticationToken = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>ApiResponse of List&lt;Ticket&gt;</returns>
        ApiResponse<List<Ticket>> PutTicketsWithHttpInfo (List<Ticket> body, bool? authenticationToken = null, string clientId = null, string clientSecret = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrievs a ticket
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken"> (optional)</param>
        /// <param name="category"> (optional)</param>
        /// <param name="statuses"> (optional)</param>
        /// <param name="orderedColumn"> (optional)</param>
        /// <param name="orderedBy"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of Ticket</returns>
        System.Threading.Tasks.Task<Ticket> GetTicketAsync (string ticketId, string authenticationToken = null, string category = null, string statuses = null, string orderedColumn = null, string orderedBy = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrievs a ticket
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken"> (optional)</param>
        /// <param name="category"> (optional)</param>
        /// <param name="statuses"> (optional)</param>
        /// <param name="orderedColumn"> (optional)</param>
        /// <param name="orderedBy"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of ApiResponse (Ticket)</returns>
        System.Threading.Tasks.Task<ApiResponse<Ticket>> GetTicketAsyncWithHttpInfo (string ticketId, string authenticationToken = null, string category = null, string statuses = null, string orderedColumn = null, string orderedBy = null, string clientId = null, string clientSecret = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="start">Start query value (optional)</param>
        /// <param name="length">Number of rows query (optional)</param>
        /// <param name="draw">Number of times table has been reloaded (optional)</param>
        /// <param name="q">Values provided in q are tokenized and search on columns: TICKET_ID,SUBJECT,REQUESTOR_UERNAME, REQUESTOR_EMAIL, TICKET_MESSAGES (optional)</param>
        /// <param name="sortBy">Column name to order table by (optional)</param>
        /// <param name="sortByOrder">Sort by ascending or descending (optional)</param>
        /// <param name="passedAccountId"> (optional)</param>
        /// <param name="passedUserId"> (optional)</param>
        /// <param name="viewId">View Id (optional)</param>
        /// <param name="clientId">API ID (optional)</param>
        /// <param name="clientSecret">API Secret (optional)</param>
        /// <returns>Task of List&lt;Ticket&gt;</returns>
        System.Threading.Tasks.Task<List<Ticket>> GetTicketsAsync (decimal? authenticationToken = null, int? start = null, int? length = null, int? draw = null, string q = null, string sortBy = null, string sortByOrder = null, string passedAccountId = null, string passedUserId = null, int? viewId = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="start">Start query value (optional)</param>
        /// <param name="length">Number of rows query (optional)</param>
        /// <param name="draw">Number of times table has been reloaded (optional)</param>
        /// <param name="q">Values provided in q are tokenized and search on columns: TICKET_ID,SUBJECT,REQUESTOR_UERNAME, REQUESTOR_EMAIL, TICKET_MESSAGES (optional)</param>
        /// <param name="sortBy">Column name to order table by (optional)</param>
        /// <param name="sortByOrder">Sort by ascending or descending (optional)</param>
        /// <param name="passedAccountId"> (optional)</param>
        /// <param name="passedUserId"> (optional)</param>
        /// <param name="viewId">View Id (optional)</param>
        /// <param name="clientId">API ID (optional)</param>
        /// <param name="clientSecret">API Secret (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Ticket&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Ticket>>> GetTicketsAsyncWithHttpInfo (decimal? authenticationToken = null, int? start = null, int? length = null, int? draw = null, string q = null, string sortBy = null, string sortByOrder = null, string passedAccountId = null, string passedUserId = null, int? viewId = null, string clientId = null, string clientSecret = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Insert a messages
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken">User athentication (optional)</param>
        /// <param name="clientId">api client (optional)</param>
        /// <param name="clientSecret">api secret (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PostMessagesAsync (Ticket body, string ticketId, string authenticationToken = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Insert a messages
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken">User athentication (optional)</param>
        /// <param name="clientId">api client (optional)</param>
        /// <param name="clientSecret">api secret (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PostMessagesAsyncWithHttpInfo (Ticket body, string ticketId, string authenticationToken = null, string clientId = null, string clientSecret = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Insert a tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of Ticket</returns>
        System.Threading.Tasks.Task<Ticket> PostTicketsAsync (List<TicketMessage> body, decimal? authenticationToken = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Insert a tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of ApiResponse (Ticket)</returns>
        System.Threading.Tasks.Task<ApiResponse<Ticket>> PostTicketsAsyncWithHttpInfo (List<TicketMessage> body, decimal? authenticationToken = null, string clientId = null, string clientSecret = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of List&lt;Ticket&gt;</returns>
        System.Threading.Tasks.Task<List<Ticket>> PutTicketsAsync (List<Ticket> body, bool? authenticationToken = null, string clientId = null, string clientSecret = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update tickets
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Ticket&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Ticket>>> PutTicketsAsyncWithHttpInfo (List<Ticket> body, bool? authenticationToken = null, string clientId = null, string clientSecret = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDefaultApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DefaultApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Retrievs a ticket
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken"> (optional)</param>
        /// <param name="category"> (optional)</param>
        /// <param name="statuses"> (optional)</param>
        /// <param name="orderedColumn"> (optional)</param>
        /// <param name="orderedBy"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Ticket</returns>
        public Ticket GetTicket (string ticketId, string authenticationToken = null, string category = null, string statuses = null, string orderedColumn = null, string orderedBy = null, string clientId = null, string clientSecret = null)
        {
             ApiResponse<Ticket> localVarResponse = GetTicketWithHttpInfo(ticketId, authenticationToken, category, statuses, orderedColumn, orderedBy, clientId, clientSecret);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrievs a ticket
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken"> (optional)</param>
        /// <param name="category"> (optional)</param>
        /// <param name="statuses"> (optional)</param>
        /// <param name="orderedColumn"> (optional)</param>
        /// <param name="orderedBy"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>ApiResponse of Ticket</returns>
        public ApiResponse< Ticket > GetTicketWithHttpInfo (string ticketId, string authenticationToken = null, string category = null, string statuses = null, string orderedColumn = null, string orderedBy = null, string clientId = null, string clientSecret = null)
        {
            // verify the required parameter 'ticketId' is set
            if (ticketId == null)
                throw new ApiException(400, "Missing required parameter 'ticketId' when calling DefaultApi->GetTicket");

            var localVarPath = "/tickets/{ticket_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticketId != null) localVarPathParams.Add("ticket_id", Configuration.ApiClient.ParameterToString(ticketId)); // path parameter
            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (category != null) localVarQueryParams.Add("category", Configuration.ApiClient.ParameterToString(category)); // query parameter
            if (statuses != null) localVarQueryParams.Add("statuses", Configuration.ApiClient.ParameterToString(statuses)); // query parameter
            if (orderedColumn != null) localVarQueryParams.Add("ordered_column", Configuration.ApiClient.ParameterToString(orderedColumn)); // query parameter
            if (orderedBy != null) localVarQueryParams.Add("ordered_by", Configuration.ApiClient.ParameterToString(orderedBy)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTicket", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Ticket>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Ticket) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Ticket)));
        }

        /// <summary>
        ///  Retrievs a ticket
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken"> (optional)</param>
        /// <param name="category"> (optional)</param>
        /// <param name="statuses"> (optional)</param>
        /// <param name="orderedColumn"> (optional)</param>
        /// <param name="orderedBy"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of Ticket</returns>
        public async System.Threading.Tasks.Task<Ticket> GetTicketAsync (string ticketId, string authenticationToken = null, string category = null, string statuses = null, string orderedColumn = null, string orderedBy = null, string clientId = null, string clientSecret = null)
        {
             ApiResponse<Ticket> localVarResponse = await GetTicketAsyncWithHttpInfo(ticketId, authenticationToken, category, statuses, orderedColumn, orderedBy, clientId, clientSecret);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Retrievs a ticket
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken"> (optional)</param>
        /// <param name="category"> (optional)</param>
        /// <param name="statuses"> (optional)</param>
        /// <param name="orderedColumn"> (optional)</param>
        /// <param name="orderedBy"> (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of ApiResponse (Ticket)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Ticket>> GetTicketAsyncWithHttpInfo (string ticketId, string authenticationToken = null, string category = null, string statuses = null, string orderedColumn = null, string orderedBy = null, string clientId = null, string clientSecret = null)
        {
            // verify the required parameter 'ticketId' is set
            if (ticketId == null)
                throw new ApiException(400, "Missing required parameter 'ticketId' when calling DefaultApi->GetTicket");

            var localVarPath = "/tickets/{ticket_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticketId != null) localVarPathParams.Add("ticket_id", Configuration.ApiClient.ParameterToString(ticketId)); // path parameter
            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (category != null) localVarQueryParams.Add("category", Configuration.ApiClient.ParameterToString(category)); // query parameter
            if (statuses != null) localVarQueryParams.Add("statuses", Configuration.ApiClient.ParameterToString(statuses)); // query parameter
            if (orderedColumn != null) localVarQueryParams.Add("ordered_column", Configuration.ApiClient.ParameterToString(orderedColumn)); // query parameter
            if (orderedBy != null) localVarQueryParams.Add("ordered_by", Configuration.ApiClient.ParameterToString(orderedBy)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTicket", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Ticket>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Ticket) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Ticket)));
        }

        /// <summary>
        ///  Retrieve tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="start">Start query value (optional)</param>
        /// <param name="length">Number of rows query (optional)</param>
        /// <param name="draw">Number of times table has been reloaded (optional)</param>
        /// <param name="q">Values provided in q are tokenized and search on columns: TICKET_ID,SUBJECT,REQUESTOR_UERNAME, REQUESTOR_EMAIL, TICKET_MESSAGES (optional)</param>
        /// <param name="sortBy">Column name to order table by (optional)</param>
        /// <param name="sortByOrder">Sort by ascending or descending (optional)</param>
        /// <param name="passedAccountId"> (optional)</param>
        /// <param name="passedUserId"> (optional)</param>
        /// <param name="viewId">View Id (optional)</param>
        /// <param name="clientId">API ID (optional)</param>
        /// <param name="clientSecret">API Secret (optional)</param>
        /// <returns>List&lt;Ticket&gt;</returns>
        public List<Ticket> GetTickets (decimal? authenticationToken = null, int? start = null, int? length = null, int? draw = null, string q = null, string sortBy = null, string sortByOrder = null, string passedAccountId = null, string passedUserId = null, int? viewId = null, string clientId = null, string clientSecret = null)
        {
             ApiResponse<List<Ticket>> localVarResponse = GetTicketsWithHttpInfo(authenticationToken, start, length, draw, q, sortBy, sortByOrder, passedAccountId, passedUserId, viewId, clientId, clientSecret);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrieve tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="start">Start query value (optional)</param>
        /// <param name="length">Number of rows query (optional)</param>
        /// <param name="draw">Number of times table has been reloaded (optional)</param>
        /// <param name="q">Values provided in q are tokenized and search on columns: TICKET_ID,SUBJECT,REQUESTOR_UERNAME, REQUESTOR_EMAIL, TICKET_MESSAGES (optional)</param>
        /// <param name="sortBy">Column name to order table by (optional)</param>
        /// <param name="sortByOrder">Sort by ascending or descending (optional)</param>
        /// <param name="passedAccountId"> (optional)</param>
        /// <param name="passedUserId"> (optional)</param>
        /// <param name="viewId">View Id (optional)</param>
        /// <param name="clientId">API ID (optional)</param>
        /// <param name="clientSecret">API Secret (optional)</param>
        /// <returns>ApiResponse of List&lt;Ticket&gt;</returns>
        public ApiResponse< List<Ticket> > GetTicketsWithHttpInfo (decimal? authenticationToken = null, int? start = null, int? length = null, int? draw = null, string q = null, string sortBy = null, string sortByOrder = null, string passedAccountId = null, string passedUserId = null, int? viewId = null, string clientId = null, string clientSecret = null)
        {

            var localVarPath = "/tickets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (start != null) localVarQueryParams.Add("start", Configuration.ApiClient.ParameterToString(start)); // query parameter
            if (length != null) localVarQueryParams.Add("length", Configuration.ApiClient.ParameterToString(length)); // query parameter
            if (draw != null) localVarQueryParams.Add("draw", Configuration.ApiClient.ParameterToString(draw)); // query parameter
            if (q != null) localVarQueryParams.Add("q", Configuration.ApiClient.ParameterToString(q)); // query parameter
            if (sortBy != null) localVarQueryParams.Add("sort_by", Configuration.ApiClient.ParameterToString(sortBy)); // query parameter
            if (sortByOrder != null) localVarQueryParams.Add("sort_by_order", Configuration.ApiClient.ParameterToString(sortByOrder)); // query parameter
            if (passedAccountId != null) localVarQueryParams.Add("passed_account_id", Configuration.ApiClient.ParameterToString(passedAccountId)); // query parameter
            if (passedUserId != null) localVarQueryParams.Add("passed_user_id", Configuration.ApiClient.ParameterToString(passedUserId)); // query parameter
            if (viewId != null) localVarQueryParams.Add("view_id", Configuration.ApiClient.ParameterToString(viewId)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTickets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Ticket>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Ticket>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Ticket>)));
        }

        /// <summary>
        ///  Retrieve tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="start">Start query value (optional)</param>
        /// <param name="length">Number of rows query (optional)</param>
        /// <param name="draw">Number of times table has been reloaded (optional)</param>
        /// <param name="q">Values provided in q are tokenized and search on columns: TICKET_ID,SUBJECT,REQUESTOR_UERNAME, REQUESTOR_EMAIL, TICKET_MESSAGES (optional)</param>
        /// <param name="sortBy">Column name to order table by (optional)</param>
        /// <param name="sortByOrder">Sort by ascending or descending (optional)</param>
        /// <param name="passedAccountId"> (optional)</param>
        /// <param name="passedUserId"> (optional)</param>
        /// <param name="viewId">View Id (optional)</param>
        /// <param name="clientId">API ID (optional)</param>
        /// <param name="clientSecret">API Secret (optional)</param>
        /// <returns>Task of List&lt;Ticket&gt;</returns>
        public async System.Threading.Tasks.Task<List<Ticket>> GetTicketsAsync (decimal? authenticationToken = null, int? start = null, int? length = null, int? draw = null, string q = null, string sortBy = null, string sortByOrder = null, string passedAccountId = null, string passedUserId = null, int? viewId = null, string clientId = null, string clientSecret = null)
        {
             ApiResponse<List<Ticket>> localVarResponse = await GetTicketsAsyncWithHttpInfo(authenticationToken, start, length, draw, q, sortBy, sortByOrder, passedAccountId, passedUserId, viewId, clientId, clientSecret);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Retrieve tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="start">Start query value (optional)</param>
        /// <param name="length">Number of rows query (optional)</param>
        /// <param name="draw">Number of times table has been reloaded (optional)</param>
        /// <param name="q">Values provided in q are tokenized and search on columns: TICKET_ID,SUBJECT,REQUESTOR_UERNAME, REQUESTOR_EMAIL, TICKET_MESSAGES (optional)</param>
        /// <param name="sortBy">Column name to order table by (optional)</param>
        /// <param name="sortByOrder">Sort by ascending or descending (optional)</param>
        /// <param name="passedAccountId"> (optional)</param>
        /// <param name="passedUserId"> (optional)</param>
        /// <param name="viewId">View Id (optional)</param>
        /// <param name="clientId">API ID (optional)</param>
        /// <param name="clientSecret">API Secret (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Ticket&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Ticket>>> GetTicketsAsyncWithHttpInfo (decimal? authenticationToken = null, int? start = null, int? length = null, int? draw = null, string q = null, string sortBy = null, string sortByOrder = null, string passedAccountId = null, string passedUserId = null, int? viewId = null, string clientId = null, string clientSecret = null)
        {

            var localVarPath = "/tickets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (start != null) localVarQueryParams.Add("start", Configuration.ApiClient.ParameterToString(start)); // query parameter
            if (length != null) localVarQueryParams.Add("length", Configuration.ApiClient.ParameterToString(length)); // query parameter
            if (draw != null) localVarQueryParams.Add("draw", Configuration.ApiClient.ParameterToString(draw)); // query parameter
            if (q != null) localVarQueryParams.Add("q", Configuration.ApiClient.ParameterToString(q)); // query parameter
            if (sortBy != null) localVarQueryParams.Add("sort_by", Configuration.ApiClient.ParameterToString(sortBy)); // query parameter
            if (sortByOrder != null) localVarQueryParams.Add("sort_by_order", Configuration.ApiClient.ParameterToString(sortByOrder)); // query parameter
            if (passedAccountId != null) localVarQueryParams.Add("passed_account_id", Configuration.ApiClient.ParameterToString(passedAccountId)); // query parameter
            if (passedUserId != null) localVarQueryParams.Add("passed_user_id", Configuration.ApiClient.ParameterToString(passedUserId)); // query parameter
            if (viewId != null) localVarQueryParams.Add("view_id", Configuration.ApiClient.ParameterToString(viewId)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTickets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Ticket>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Ticket>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Ticket>)));
        }

        /// <summary>
        ///  Insert a messages
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken">User athentication (optional)</param>
        /// <param name="clientId">api client (optional)</param>
        /// <param name="clientSecret">api secret (optional)</param>
        /// <returns></returns>
        public void PostMessages (Ticket body, string ticketId, string authenticationToken = null, string clientId = null, string clientSecret = null)
        {
             PostMessagesWithHttpInfo(body, ticketId, authenticationToken, clientId, clientSecret);
        }

        /// <summary>
        ///  Insert a messages
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken">User athentication (optional)</param>
        /// <param name="clientId">api client (optional)</param>
        /// <param name="clientSecret">api secret (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> PostMessagesWithHttpInfo (Ticket body, string ticketId, string authenticationToken = null, string clientId = null, string clientSecret = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->PostMessages");
            // verify the required parameter 'ticketId' is set
            if (ticketId == null)
                throw new ApiException(400, "Missing required parameter 'ticketId' when calling DefaultApi->PostMessages");

            var localVarPath = "/tickets/{ticket_id}/messages";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticketId != null) localVarPathParams.Add("ticket_id", Configuration.ApiClient.ParameterToString(ticketId)); // path parameter
            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostMessages", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        ///  Insert a messages
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken">User athentication (optional)</param>
        /// <param name="clientId">api client (optional)</param>
        /// <param name="clientSecret">api secret (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PostMessagesAsync (Ticket body, string ticketId, string authenticationToken = null, string clientId = null, string clientSecret = null)
        {
             await PostMessagesAsyncWithHttpInfo(body, ticketId, authenticationToken, clientId, clientSecret);

        }

        /// <summary>
        ///  Insert a messages
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="ticketId"></param>
        /// <param name="authenticationToken">User athentication (optional)</param>
        /// <param name="clientId">api client (optional)</param>
        /// <param name="clientSecret">api secret (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> PostMessagesAsyncWithHttpInfo (Ticket body, string ticketId, string authenticationToken = null, string clientId = null, string clientSecret = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->PostMessages");
            // verify the required parameter 'ticketId' is set
            if (ticketId == null)
                throw new ApiException(400, "Missing required parameter 'ticketId' when calling DefaultApi->PostMessages");

            var localVarPath = "/tickets/{ticket_id}/messages";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticketId != null) localVarPathParams.Add("ticket_id", Configuration.ApiClient.ParameterToString(ticketId)); // path parameter
            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostMessages", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        ///  Insert a tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Ticket</returns>
        public Ticket PostTickets (List<TicketMessage> body, decimal? authenticationToken = null, string clientId = null, string clientSecret = null)
        {
             ApiResponse<Ticket> localVarResponse = PostTicketsWithHttpInfo(body, authenticationToken, clientId, clientSecret);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Insert a tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>ApiResponse of Ticket</returns>
        public ApiResponse< Ticket > PostTicketsWithHttpInfo (List<TicketMessage> body, decimal? authenticationToken = null, string clientId = null, string clientSecret = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->PostTickets");

            var localVarPath = "/tickets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostTickets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Ticket>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Ticket) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Ticket)));
        }

        /// <summary>
        ///  Insert a tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of Ticket</returns>
        public async System.Threading.Tasks.Task<Ticket> PostTicketsAsync (List<TicketMessage> body, decimal? authenticationToken = null, string clientId = null, string clientSecret = null)
        {
             ApiResponse<Ticket> localVarResponse = await PostTicketsAsyncWithHttpInfo(body, authenticationToken, clientId, clientSecret);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Insert a tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of ApiResponse (Ticket)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Ticket>> PostTicketsAsyncWithHttpInfo (List<TicketMessage> body, decimal? authenticationToken = null, string clientId = null, string clientSecret = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->PostTickets");

            var localVarPath = "/tickets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostTickets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Ticket>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Ticket) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Ticket)));
        }

        /// <summary>
        ///  Update tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>List&lt;Ticket&gt;</returns>
        public List<Ticket> PutTickets (List<Ticket> body, bool? authenticationToken = null, string clientId = null, string clientSecret = null)
        {
             ApiResponse<List<Ticket>> localVarResponse = PutTicketsWithHttpInfo(body, authenticationToken, clientId, clientSecret);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Update tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>ApiResponse of List&lt;Ticket&gt;</returns>
        public ApiResponse< List<Ticket> > PutTicketsWithHttpInfo (List<Ticket> body, bool? authenticationToken = null, string clientId = null, string clientSecret = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->PutTickets");

            var localVarPath = "/tickets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutTickets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Ticket>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Ticket>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Ticket>)));
        }

        /// <summary>
        ///  Update tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of List&lt;Ticket&gt;</returns>
        public async System.Threading.Tasks.Task<List<Ticket>> PutTicketsAsync (List<Ticket> body, bool? authenticationToken = null, string clientId = null, string clientSecret = null)
        {
             ApiResponse<List<Ticket>> localVarResponse = await PutTicketsAsyncWithHttpInfo(body, authenticationToken, clientId, clientSecret);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Update tickets
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request body for the operation</param>
        /// <param name="authenticationToken">User athentication uuid (optional)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Ticket&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Ticket>>> PutTicketsAsyncWithHttpInfo (List<Ticket> body, bool? authenticationToken = null, string clientId = null, string clientSecret = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->PutTickets");

            var localVarPath = "/tickets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authenticationToken != null) localVarQueryParams.Add("authentication_token", Configuration.ApiClient.ParameterToString(authenticationToken)); // query parameter
            if (clientId != null) localVarQueryParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // query parameter
            if (clientSecret != null) localVarQueryParams.Add("client_secret", Configuration.ApiClient.ParameterToString(clientSecret)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutTickets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Ticket>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Ticket>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Ticket>)));
        }

    }
}
